const localizationConstants = {
  en: {
    choose_location: 'Choose your location',
    curr_location: 'Current Location',
    vienna: 'Vienna',
    poertschach: 'Pörtschach am Wörthersee',
    hallstatt: 'Hallstatt',
    stubaital: 'Stubaital',
    salzburg: 'Salzburg',
    change_location: 'Change Location',
    no_location: 'No location selected!',
    radius: 'Search radius',
    search: 'Search',
    suggestions: 'Suggestions',
    results: 'Results found',
    of: 'of',
    home_page: 'Home Page',
    back: 'Back',
    search_terms: 'Search Terms',
    not_supported: 'Geolocation is not supported by this browser.',
    location_denied: 'You denied the request for Geolocation.',
    location_unavailable: 'Location information is unavailable.',
    location_timeout: 'The request to get user location timed out.',
    unknown_error: 'An unknown error occurred.',
    error: 'Error',
    no_results: 'No results found!',
  },
  de: {
    choose_location: 'Wählen Sie deinen Standort',
    curr_location: 'Aktueller Standort',
    vienna: 'Wien',
    poertschach: 'Pörtschach am Wörthersee',
    hallstatt: 'Hallstatt',
    stubaital: 'Stubaital',
    salzburg: 'Salzburg',
    change_location: 'Standort ändern',
    no_location: 'Kein Standort ausgewählt!',
    radius: 'Suchradius',
    search: 'Suchen',
    suggestions: 'Vorschläge',
    results: 'Ergebnisse gefunden',
    of: 'von',
    home_page: 'Startseite',
    back: 'Zurück',
    search_terms: 'Suchbegriffe',
    not_supported: 'Geolocation wird von diesem Browser nicht unterstützt.',
    location_denied: 'Sie haben die Anfrage zur Standortbestimmung abgelehnt.',
    location_unavailable: 'Standortinformationen sind nicht verfügbar.',
    location_timeout: 'Die Anfrage zum Abrufen des Benutzerstandorts ist abgelaufen.',
    unknown_error: 'Ein unbekannter Fehler ist aufgetreten.',
    error: 'Fehler',
    no_results: 'Keine Ergebnisse gefunden!',
  },
};
export default localizationConstants;
