const localizationConstants = {
  en: {
    choose_location: 'Choose your location',
    curr_location: 'Current Location',
    vienna: 'Vienna',
    change_location: 'Change Location',
    no_location: 'No location selected!',
    radius: 'Search radius',
    search: 'Search',
    suggestions: 'Suggestions',
    results: 'Results found',
    of: 'of',
    home_page: 'Home Page',
    back: 'Back',
    search_terms: 'Search Terms',
  },
  de: {
    choose_location: 'Wählen Sie deinen Standort',
    curr_location: 'Aktueller Standort',
    vienna: 'Wien',
    change_location: 'Standort ändern',
    no_location: 'Kein Standort ausgewählt!',
    radius: 'Suchradius',
    search: 'Suchen',
    suggestions: 'Vorschläge',
    results: 'Ergebnisse gefunden',
    of: 'von',
    home_page: 'Startseite',
    back: 'Zurück',
    search_terms: 'Suchbegriffe',
  },
};
export default localizationConstants;
